-- MySQL Script generated by MySQL Workbench
-- Sun May 26 16:55:53 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema AG
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema AG
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `AG` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `AG` ;

-- -----------------------------------------------------
-- Table `AG`.`Population`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AG`.`Population` (
  `fips` INT NOT NULL,
  `year` INT NOT NULL,
  `population` INT NULL,
  PRIMARY KEY ( `fips`, `year`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AG`.`AgePopulation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AG`.`AgePopulation` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `fips` INT NOT NULL,
  `year` INT NOT NULL,
  `age0_population` INT NULL DEFAULT NULL,
  `age1_population` INT NULL DEFAULT NULL,
  `age2_population` INT NULL DEFAULT NULL,
  `age3_population` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fips_idx` (`fips` ASC, `year` ASC) VISIBLE,
  CONSTRAINT `fips`
    FOREIGN KEY (`fips` , `year`)
    REFERENCES `AG`.`Population` (`fips` , `year`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `AG`.`AgePopulationContinued`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AG`.`AgePopulationContinued` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `fips` INT NOT NULL,
  `year` INT NOT NULL,
  `age4_population` INT NULL DEFAULT NULL,
  `age5_population` INT NULL DEFAULT NULL,
  `age6_population` INT NULL DEFAULT NULL,
  `age7_population` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fips_idx` (`id` ASC, `fips` ASC, `year` ASC) VISIBLE,
  CONSTRAINT `fips1`
    FOREIGN KEY (`fips` , `year`)
    REFERENCES `AG`.`Population` (`fips` , `year`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `AG`.`AgePopulationContinued2`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AG`.`AgePopulationContinued2` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `fips` INT NOT NULL,
  `year` INT NOT NULL,
  `age8_population` INT NULL DEFAULT NULL,
  `age9_population` INT NULL DEFAULT NULL,
  `age10_population` INT NULL DEFAULT NULL,
  `age11_population` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fips_idx` (`fips` ASC, `year` ASC) VISIBLE,
  CONSTRAINT `fips2`
    FOREIGN KEY (`fips` , `year`)
    REFERENCES `AG`.`Population` (`fips` , `year`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `AG`.`AgePopulationContinued3`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AG`.`AgePopulationContinued3` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `fips` INT NOT NULL,
  `year` INT NOT NULL,
  `age12_population` INT NULL DEFAULT NULL,
  `age13_population` INT NULL DEFAULT NULL,
  `age14_population` INT NULL DEFAULT NULL,
  `age15_population` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fips_idx` (`fips` ASC, `year` ASC) VISIBLE,
  CONSTRAINT `fip3`
    FOREIGN KEY (`fips` , `year`)
    REFERENCES `AG`.`Population` (`fips` , `year`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `AG`.`AgePopulationContinued4`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AG`.`AgePopulationContinued4` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `fips` INT NOT NULL,
  `year` INT NOT NULL,
  `age16_population` INT NULL DEFAULT NULL,
  `age17_population` INT NULL DEFAULT NULL,
  `age18_population` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fips_idx` (`fips` ASC, `year` ASC) VISIBLE,
  CONSTRAINT `fips4`
    FOREIGN KEY (`fips` , `year`)
    REFERENCES `AG`.`Population` (`fips` , `year`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `AG`.`AgePopulationRatio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AG`.`AgePopulationRatio` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `fips` INT NOT NULL,
  `year` INT NOT NULL,
  `age0_population_ratio` FLOAT NULL DEFAULT NULL,
  `age1_population_ratio` FLOAT NULL DEFAULT NULL,
  `age2_population_ratio` FLOAT NULL DEFAULT NULL,
  `age3_population_ratio` FLOAT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fips_idx` (`fips` ASC, `year` ASC) VISIBLE,
  CONSTRAINT `fips5`
    FOREIGN KEY (`fips` , `year`)
    REFERENCES `AG`.`Population` (`fips` , `year`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `AG`.`AgePopulationRatioContinued`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AG`.`AgePopulationRatioContinued` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `fips` INT NOT NULL,
  `year` INT NOT NULL,
  `age4_population_ratio` FLOAT NULL DEFAULT NULL,
  `age5_population_ratio` FLOAT NULL DEFAULT NULL,
  `age6_population_ratio` FLOAT NULL DEFAULT NULL,
  `age7_population_ratio` FLOAT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fips_idx` (`fips` ASC, `year` ASC) VISIBLE,
  CONSTRAINT `fips6`
    FOREIGN KEY (`fips` , `year`)
    REFERENCES `AG`.`Population` (`fips` , `year`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `AG`.`AgePopulationRatioContinued2`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AG`.`AgePopulationRatioContinued2` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `fips` INT NOT NULL,
  `year` INT NOT NULL,
  `age8_population_ratio` FLOAT NULL DEFAULT NULL,
  `age9_population_ratio` FLOAT NULL DEFAULT NULL,
  `age10_population_ratio` FLOAT NULL DEFAULT NULL,
  `age11_population_ratio` FLOAT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fips_idx` (`fips` ASC, `year` ASC) VISIBLE,
  CONSTRAINT `fips7`
    FOREIGN KEY (`fips` , `year`)
    REFERENCES `AG`.`Population` (`fips` , `year`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `AG`.`AgePopulationRatioContinued3`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AG`.`AgePopulationRatioContinued3` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `fips` INT NOT NULL,
  `year` INT NOT NULL,
  `age12_population_ratio` FLOAT NULL DEFAULT NULL,
  `age13_population_ratio` FLOAT NULL DEFAULT NULL,
  `age14_population_ratio` FLOAT NULL DEFAULT NULL,
  `age15_population_ratio` FLOAT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fips_idx` (`fips` ASC, `year` ASC) VISIBLE,
  CONSTRAINT `fips8`
    FOREIGN KEY (`fips` , `year`)
    REFERENCES `AG`.`Population` (`fips` , `year`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `AG`.`AgePopulationRatioContinued4`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AG`.`AgePopulationRatioContinued4` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `fips` INT NOT NULL,
  `year` INT NOT NULL,
  `age16_population_ratio` FLOAT NULL DEFAULT NULL,
  `age17_population_ratio` FLOAT NULL DEFAULT NULL,
  `age18_population_ratio` FLOAT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fips_idx` (`fips` ASC, `year` ASC) VISIBLE,
  CONSTRAINT `fips9`
    FOREIGN KEY (`fips` , `year`)
    REFERENCES `AG`.`Population` (`fips` , `year`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `AG`.`RacePopulation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AG`.`RacePopulation` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `fips` INT NOT NULL,
  `year` INT NOT NULL,
  `w_population` INT NULL DEFAULT NULL,
  `b_population` INT NULL DEFAULT NULL,
  `o_population` INT NULL DEFAULT NULL,
  INDEX `fips_idx` (`fips` ASC, `year` ASC) VISIBLE,
  PRIMARY KEY (`id`),
  CONSTRAINT `fips10`
    FOREIGN KEY (`fips` , `year`)
    REFERENCES `AG`.`Population` (`fips` , `year`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `AG`.`OriginPopulation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AG`.`OriginPopulation` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `fips` INT NOT NULL,
  `year` INT NOT NULL,
  `nh_population` INT NULL,
  `hi_population` INT NULL DEFAULT NULL,
  `na_population` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fips_idx` (`fips` ASC, `year` ASC) INVISIBLE,
  CONSTRAINT `fips11`
    FOREIGN KEY (`fips` , `year`)
    REFERENCES `AG`.`Population` (`fips` , `year`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `AG`.`GenderPopulationRatio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AG`.`GenderPopulationRatio` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `fips` INT NOT NULL,
  `year` INT NOT NULL,
  `male_population_ratio` FLOAT NULL DEFAULT NULL,
  `female_population_ratio` FLOAT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fips_idx` (`fips` ASC, `year` ASC) INVISIBLE,
  CONSTRAINT `fips12`
    FOREIGN KEY (`fips` , `year`)
    REFERENCES `AG`.`Population` (`fips` , `year`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `AG`.`SexPopulation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AG`.`SexPopulation` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `fips` INT NOT NULL,
  `year` INT NOT NULL,
  `mail_population` INT NULL DEFAULT NULL,
  `femail_population` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fips_idx` (`fips` ASC, `year` ASC) VISIBLE,
  CONSTRAINT `fips13`
    FOREIGN KEY (`fips` , `year`)
    REFERENCES `AG`.`Population` (`fips` , `year`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `AG`.`PopulationRatio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AG`.`PopulationRatio` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `fips` INT NOT NULL,
  `year` INT NOT NULL,
  `w_population_ratio` FLOAT NULL DEFAULT NULL,
  `b_population_ratio` FLOAT NULL DEFAULT NULL,
  `o_population_ratio` FLOAT NULL DEFAULT NULL,
  `nh_population_ratio` FLOAT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fips_idx` (`fips` ASC, `year` ASC) VISIBLE,
  CONSTRAINT `fips14`
    FOREIGN KEY (`fips` , `year`)
    REFERENCES `AG`.`Population` (`fips` , `year`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `AG`.`PopulationRatioContinued`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AG`.`PopulationRatioContinued` (
  `id` INT NOT NULL,
  `fips` INT NOT NULL,
  `year` INT NOT NULL,
  `hi_population_ratio` FLOAT NULL DEFAULT NULL,
  `na_population_ratio` FLOAT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fips_idx` (`fips` ASC, `year` ASC) VISIBLE,
  CONSTRAINT `fips15`
    FOREIGN KEY (`fips`, `year`)
    REFERENCES `AG`.`Population` ( `fips`, `year`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `AG`.`county_demographics`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AG`.`county_demographics` (
  `year` INT NULL DEFAULT NULL,
  `fips` INT NULL DEFAULT NULL,
  `population` INT NULL DEFAULT NULL,
  `w_population` INT NULL DEFAULT NULL,
  `b_population` INT NULL DEFAULT NULL,
  `o_population` INT NULL DEFAULT NULL,
  `nh_population` INT NULL DEFAULT NULL,
  `hi_population` INT NULL DEFAULT NULL,
  `na_population` INT NULL DEFAULT NULL,
  `male_population` INT NULL DEFAULT NULL,
  `female_population` INT NULL DEFAULT NULL,
  `age0_population` INT NULL DEFAULT NULL,
  `age1_population` INT NULL DEFAULT NULL,
  `age2_population` INT NULL DEFAULT NULL,
  `age3_population` INT NULL DEFAULT NULL,
  `age4_population` INT NULL DEFAULT NULL,
  `age5_population` INT NULL DEFAULT NULL,
  `age6_population` INT NULL DEFAULT NULL,
  `age7_population` INT NULL DEFAULT NULL,
  `age8_population` INT NULL DEFAULT NULL,
  `age9_population` INT NULL DEFAULT NULL,
  `age10_population` INT NULL DEFAULT NULL,
  `age11_population` INT NULL DEFAULT NULL,
  `age12_population` INT NULL DEFAULT NULL,
  `age13_population` INT NULL DEFAULT NULL,
  `age14_population` INT NULL DEFAULT NULL,
  `age15_population` INT NULL DEFAULT NULL,
  `age16_population` INT NULL DEFAULT NULL,
  `age17_population` INT NULL DEFAULT NULL,
  `age18_population` INT NULL DEFAULT NULL,
  `w_population_ratio` DOUBLE NULL DEFAULT NULL,
  `b_population_ratio` DOUBLE NULL DEFAULT NULL,
  `o_population_ratio` DOUBLE NULL DEFAULT NULL,
  `nh_population_ratio` DOUBLE NULL DEFAULT NULL,
  `hi_population_ratio` DOUBLE NULL DEFAULT NULL,
  `na_population_ratio` DOUBLE NULL DEFAULT NULL,
  `male_population_ratio` DOUBLE NULL DEFAULT NULL,
  `female_population_ratio` DOUBLE NULL DEFAULT NULL,
  `age0_population_ratio` DOUBLE NULL DEFAULT NULL,
  `age1_population_ratio` DOUBLE NULL DEFAULT NULL,
  `age2_population_ratio` DOUBLE NULL DEFAULT NULL,
  `age3_population_ratio` DOUBLE NULL DEFAULT NULL,
  `age4_population_ratio` DOUBLE NULL DEFAULT NULL,
  `age5_population_ratio` DOUBLE NULL DEFAULT NULL,
  `age6_population_ratio` DOUBLE NULL DEFAULT NULL,
  `age7_population_ratio` DOUBLE NULL DEFAULT NULL,
  `age8_population_ratio` DOUBLE NULL DEFAULT NULL,
  `age9_population_ratio` DOUBLE NULL DEFAULT NULL,
  `age10_population_ratio` DOUBLE NULL DEFAULT NULL,
  `age11_population_ratio` DOUBLE NULL DEFAULT NULL,
  `age12_population_ratio` DOUBLE NULL DEFAULT NULL,
  `age13_population_ratio` DOUBLE NULL DEFAULT NULL,
  `age14_population_ratio` DOUBLE NULL DEFAULT NULL,
  `age15_population_ratio` DOUBLE NULL DEFAULT NULL,
  `age16_population_ratio` DOUBLE NULL DEFAULT NULL,
  `age17_population_ratio` DOUBLE NULL DEFAULT NULL,
  `age18_population_ratio` DOUBLE NULL DEFAULT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
